### ISSUE TITLE
Over Telnet

### ISSUE THREAD

**Issue by fredericplante** [nottwo/BasicTerm#2]
I have been experiencing your library on an ESP8266 environnement, using VStudio as IDE and Realterm as ANSI viewer. I must say that I was pretty impressed, that why I got this Little Maze up for you.

This being sayed, I see alot of potential for this library, but we should port it so it would also work over Telnet. I got a ideas on how to intreduce it, but I like to ask the original guy his opinion, so the work stays coherent and nice.

So that is about that, and this. :D talm to you soon

**Comment by fredericplante** [comment]
Telnet would be a beguining I was also thinking about the DueVGA library from Stimmers

**Comment by fredericplante** [comment]
By the way I see it, the multi-connection aspect make you library very  hard to keep as such.  I will make a library that founded on yours, but it's main goal will be to return ansi coding and let the user code manage the rest.

**Comment by nottwo** [comment]
Hi @fredericplante, thanks for taking a look at this library.  I just got back from vacation and I'm sorry to be getting back to you just now.

My intuition is that BasicTerm should just work over telnet. The Arduino Ethernet and WiFiClient libraries are all implementations of the Stream interface, so you should be able to do something like:

```arduino
EthernetClient server = new EthernetServer(23);
Ethernet.begin(mac, ip, gateway, subnet);
server.begin();

if(server.available()) {
    BasicTerm term(server);
    term.init();
    term.cls();
    term.position(5, 5);
    term.print("welcome to the telnet server");
}
```

While I've picked up some ESP8266 devices, I haven't tried using the Arduino environment or BasicTerm with it.  I'll see what I can do up with my BlynkBoard.

It should be possible to have multiple connections by creating multiple instances of the `BasicTerm` class for each connection `Stream`.

**Comment by fredericplante** [comment]
Hey hello

I propose to make Basicterm work along the Telnet serial exemple of the ESP8266  package.

I gave it a try, not to seriously cause there were folks over, but now  I'm free now, so I will give it a bether try.

**Comment by vitasam** [comment]
Hi @nottwo ,

I've tested your great lib with [Arduino-BASIC ](https://github.com/robinhedwards/ArduinoBASIC)on Arduino-Nano, I just replaced PS/2 keyboard and OLED methods with your BasicTerm input/output, screenshot is from Minicom:
![image](https://user-images.githubusercontent.com/5597505/47957032-7c2af780-dfb7-11e8-916b-adf4574138c1.png)

One question - is there any way to delete a char? Should ANSI/VT220 terminal support backspace?

**Comment by nottwo** [comment]
Hi @vitasam ,

It's nice to hear that you've found BasicTerm useful!

BasicTerm doesn't currently offer a line-editing mode.  That would be a useful addition.

In the Unix/Linux world, this is called [line discipline](https://en.wikipedia.org/wiki/Line_discipline)

BasicTerm is currently operating in  [raw mode](https://unix.stackexchange.com/questions/21752/what-s-the-difference-between-a-raw-and-a-cooked-device-driver) and the application in responsible for handling all keyboard input itself.
